{
 "title": "Solar Bluetooth Monitor - Gauges",
 "time": { "from": "now-3d", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Battery Monitor" } },
  {
   "title": "Charge Status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "junctek_load_status", "legendFormat": "Time Remaining" }
   ]
  },
  {
   "title": "Battery (V)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "junctek_load_volts", "legendFormat": "Battery Charge" }
   ]
  },
  {
   "title": "Power (W)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "junctek_load_power_watts", "legendFormat": "Solar Watts" }
   ]
  },
  {
   "title": "Load (A)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "junctek_load_amps", "legendFormat": "Solar Watts" }
   ]
  },
  {
   "title": "Battery Charge %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "junctek_battery_percentage", "legendFormat": "Battery Charge" }
   ]
  },
  {
   "title": "aH Remaining",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "junctek_ah_remaining", "legendFormat": "aH Remaining" }
   ]
  },
  {
   "title": "Time Remaining",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "junctek_min_remaining", "legendFormat": "Time Remaining" }
   ]
  },
  { "title": " ", "type": "text", "gridPos": { "h": 2, "w": 6, "x": 18, "y": 8 }, "options": { "content": " " } },
  {
   "title": "Options",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "options": {
    "content": "<div class=\"gf-form\">\r\n  <a class=\"gf-form-label gf-form-label\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-05/solar-bluetooth-monitor-gauges?orgId=1&refresh=30s&from=now-1h&to=now&kiosk\">1h</a>\r\n  <a class=\"gf-form-label gf-form-label\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-05/solar-bluetooth-monitor-gauges?orgId=1&refresh=30s&from=now-24h&to=now&kiosk\">1d</a>\r\n  <a class=\"gf-form-label gf-form-label\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-05/solar-bluetooth-monitor-gauges?orgId=1&refresh=30s&from=now-3d&to=now&kiosk\">3d</a>\r\n  <a class=\"gf-form-label gf-form-label\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-05/solar-bluetooth-monitor-gauges?orgId=1&refresh=30s&from=now-7d&to=now&kiosk\">7d</a>\r\n  <a class=\"gf-form-label gf-form-label\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-05/solar-bluetooth-monitor-gauges?orgId=1&refresh=30s&from=now-28d&to=now&kiosk\">4w</a>\r\n</div>\r\n<div class=\"gf-form\">\r\n  <a class=\"gf-form-label gf-form-label--dashlink\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-01/solar-bluetooth-monitor?orgId=1&refresh=30s&from=now-1d&to=now&kiosk\">MAIN</a>\r\n  <a class=\"gf-form-label gf-form-label--dashlink\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-05/solar-bluetooth-monitor-gauges?orgId=1&refresh=30s&from=now-1d&to=now&kiosk\">GAUGES</a>\r\n</div>\r\n<div class=\"gf-form\">\r\n  <a class=\"gf-form-label gf-form-label--dashlink\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-04/solar-bluetooth-monitor-detailed?orgId=1&refresh=30s&from=now-3d&to=now&kiosk\">CHARTS</a>\r\n  <a class=\"gf-form-label gf-form-label--dashlink\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-03/solar-bluetooth-monitor-history?orgId=1&refresh=30s&from=now-28d&to=now&kiosk\">HISTORY</a>\r\n</div>\r\n<div class=\"gf-form\">\r\n  <a class=\"gf-form-label gf-form-label--dashlink\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-05/solar-bluetooth-monitor-gauges?orgId=1&refresh=30s&kiosk=tv\">DASH</a>\r\n  <a class=\"gf-form-label gf-form-label--dashlink\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:7800/\">EXIT</a>\r\n</div>"
   },
   "targets": [
    {}
   ]
  },
  { "title": " ", "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 14 }, "options": { "content": " " } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 }, "options": { "content": "# Solar Charge Controller" } },
  {
   "title": "Solar Charging State",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_controller_charging_state",
     "legendFormat": "Solar Panels:"
    }
   ]
  },
  {
   "title": "Solar Volts (V)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solarmon_solar_volts", "legendFormat": "Solar Volts" }
   ]
  },
  {
   "title": "Solar Power (W)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solarmon_solar_watts", "legendFormat": "Solar Watts" }
   ]
  },
  {
   "title": "Solar Amps (A)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solarmon_solar_amperes", "legendFormat": "Solar Amps" }
   ]
  },
  {
   "title": "Charging aH Today",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_charging_amp_hours_today",
     "legendFormat": "Charging aH Today"
    }
   ]
  },
  {
   "title": "Discharging aH Today",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_discharging_amp_hours_today",
     "legendFormat": "Discharging aH Today"
    }
   ]
  },
  {
   "title": "Power Generation Today",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_power_generation_today",
     "legendFormat": "Power Generation Today"
    }
   ]
  },
  {
   "title": "Max Charging Power Today",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_max_charging_power_today",
     "legendFormat": "Max Charging Power Today"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 }, "options": { "content": "# Raspberry Pi" } },
  {
   "title": "CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pi_cpu_usage", "legendFormat": "CPU" }
   ]
  },
  {
   "title": "RAM (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pi_ram_usage", "legendFormat": "RAM" }
   ]
  },
  {
   "title": "Storage (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pi_storage_usage", "legendFormat": "Storage" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 }, "options": { "content": "# Temperatures" } },
  {
   "title": "Pi Temp (C)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pi_temperature_celcius", "legendFormat": "Pi Temp" }
   ]
  },
  {
   "title": "Controler Temp (C)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_controller_temperature_celsius",
     "legendFormat": "Controler Temp"
    }
   ]
  },
  {
   "title": "Outside Temp (C)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_battery_temperature_celsius",
     "legendFormat": "Outside Temp"
    }
   ]
  },
  {
   "title": "Inside Temp (C)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "junctek_temp", "legendFormat": "Inside Temp" }
   ]
  }
 ]
}