{
 "title": "Solar Bluetooth Monitor - Detailed",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Solar Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "solarmon_solar_watts", "legendFormat": "Watts" },
    {
     "expr": " solarmon_solar_watts offset 24h",
     "legendFormat": "__auto"
    },
    {
     "expr": " solarmon_solar_watts offset 48h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Charge Today (Ah)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_charging_amp_hours_today",
     "legendFormat": "Solar Amps"
    }
   ]
  },
  {
   "title": "Discharge Today (Ah)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_discharging_amp_hours_today",
     "legendFormat": "Solar Amps"
    }
   ]
  },
  {
   "title": "Power Generation (Today)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_power_generation_today",
     "legendFormat": "Solar Amps"
    }
   ]
  },
  {
   "title": "Max Charge Today (Ah)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_max_charging_power_today",
     "legendFormat": "Solar Amps"
    }
   ]
  },
  {
   "title": "View Options",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "options": {
    "content": "<div class=\"gf-form\">\r\n  <a class=\"gf-form-label gf-form-label\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-04/solar-bluetooth-monitor-detailed?orgId=1&refresh=30s&from=now-1h&to=now&kiosk\">1h</a>\r\n  <a class=\"gf-form-label gf-form-label\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-04/solar-bluetooth-monitor-detailed?orgId=1&refresh=30s&from=now-24h&to=now&kiosk\">1d</a>\r\n  <a class=\"gf-form-label gf-form-label\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-04/solar-bluetooth-monitor-detailed?orgId=1&refresh=30s&from=now-3d&to=now&kiosk\">3d</a>\r\n  <a class=\"gf-form-label gf-form-label\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-04/solar-bluetooth-monitor-detailed?orgId=1&refresh=30s&from=now-7d&to=now&kiosk\">7d</a>\r\n  <a class=\"gf-form-label gf-form-label\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-04/solar-bluetooth-monitor-detailed?orgId=1&refresh=30s&from=now-28d&to=now&kiosk\">4w</a>\r\n</div>\r\n<div class=\"gf-form\">\r\n  <a class=\"gf-form-label gf-form-label--dashlink\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-01/solar-bluetooth-monitor?orgId=1&refresh=30s&from=now-7d&to=now&kiosk\">MAIN</a>\r\n  <a class=\"gf-form-label gf-form-label--dashlink\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-03/solar-bluetooth-monitor-history?orgId=1&refresh=30s&from=now-28d&to=now&kiosk\">HISTORY</a>\r\n</div>\r\n<div class=\"gf-form\">\r\n  \r\n  <a class=\"gf-form-label gf-form-label--dashlink\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-04/solar-bluetooth-monitor-detailed?kiosk=tv\">SHOW DASH</a>\r\n  <a class=\"gf-form-label gf-form-label--dashlink\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:7800/\">EXIT</a>\r\n</div>\r\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Load Amps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "solarmon_load_amperes", "legendFormat": "Load Amps" }
   ]
  },
  {
   "title": "Controller Temperature (C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "solarmon_controller_temperature_celsius",
     "legendFormat": "Controller Temp"
    }
   ]
  },
  {
   "title": "Raspberry Pi Temp (C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "pi_temperature_celcius", "legendFormat": "Raspberry Pi Temp" }
   ]
  },
  {
   "title": "Raspberry Pi CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "pi_cpu_usage", "legendFormat": "Raspberry Pi Temp" }
   ]
  },
  {
   "title": "Raspberry Pi RAM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "pi_ram_usage", "legendFormat": "Raspberry Pi Temp" }
   ]
  },
  {
   "title": "Raspberry Pi Storage Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "pi_storage_usage", "legendFormat": "Raspberry Pi Temp" }
   ]
  },
  {
   "title": "Battery Voltage (Lead Acid)",
   "type": "timeseries",
   "description": "Colour ranges here are specifically for Lead Acid. Disable this and use the Battery Voltage (LiFePo) chart instead if you have a LiFePo battery.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "solarmon_battery_volts", "legendFormat": "Battery Volts" }
   ]
  },
  {
   "title": "Battery Temperature (C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "solarmon_battery_temperature_celsius",
     "legendFormat": "Battery Temp"
    }
   ]
  },
  {
   "title": "Solar Volts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "solarmon_solar_volts", "legendFormat": "Volts" }
   ]
  },
  {
   "title": "Solar Amps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "solarmon_solar_amperes", "legendFormat": "Amps" }
   ]
  },
  {
   "title": "Load Volts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "solarmon_load_volts", "legendFormat": "Load Volts" }
   ]
  },
  {
   "title": "Load Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "solarmon_load_power_watts", "legendFormat": "Load Watts" }
   ]
  },
  {
   "title": "Battery Voltage (LiFePo)",
   "type": "timeseries",
   "description": "Colour ranges here are specifically for LiFePo. Disable this and use the Battery Voltage (Lead Acid) chart instead if you have a Lead Acid battery.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "solarmon_battery_volts", "legendFormat": "Battery Volts" }
   ]
  },
  {
   "title": "Battery Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "solarmon_battery_current", "legendFormat": "Battery Volts" }
   ]
  }
 ]
}