{
 "title": "Solar Bluetooth Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Battery Charge %",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solarmon_battery_percentage", "legendFormat": "Battery Charge" }
   ]
  },
  {
   "title": "Solar Volts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solarmon_solar_volts", "legendFormat": "Solar Volts" }
   ]
  },
  {
   "title": "Solar Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solarmon_solar_watts", "legendFormat": "Solar Watts" }
   ]
  },
  {
   "title": "Solar Amps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "solarmon_solar_amperes", "legendFormat": "Solar Amps" }
   ]
  },
  {
   "title": "Charging State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_controller_charging_state",
     "legendFormat": "Charge State"
    }
   ]
  },
  {
   "title": "Charge Today (Ah)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_charging_amp_hours_today",
     "legendFormat": "Solar Amps"
    }
   ]
  },
  {
   "title": "Discharge Today (Ah)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_discharging_amp_hours_today",
     "legendFormat": "Solar Amps"
    }
   ]
  },
  {
   "title": "Max Charge Today (Ah)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_max_charging_power_today",
     "legendFormat": "Solar Amps"
    }
   ]
  },
  {
   "title": "Power Generation (Today)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_power_generation_today",
     "legendFormat": "Solar Amps"
    }
   ]
  },
  {
   "title": "Power Generation (Total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_power_generation_total",
     "legendFormat": "Solar Amps"
    }
   ]
  },
  {
   "title": "Battery Charge %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "solarmon_battery_percentage" }
   ]
  },
  {
   "title": "Solar Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "solarmon_solar_watts", "legendFormat": "Watts" }
   ]
  },
  {
   "title": "Solar Volts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "solarmon_solar_volts", "legendFormat": "Volts" }
   ]
  },
  {
   "title": "Solar Amps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "solarmon_solar_amperes", "legendFormat": "Amps" }
   ]
  },
  {
   "title": "Load Watts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "solarmon_load_power_watts", "legendFormat": "Load Watts" }
   ]
  },
  {
   "title": "Load Volts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "solarmon_load_volts", "legendFormat": "Load Watts" }
   ]
  },
  {
   "title": "Load Amps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "solarmon_load_amperes", "legendFormat": "Load Amps" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "solarmon_battery_volts", "legendFormat": "Battery Volts" }
   ]
  },
  {
   "title": "Battery Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "solarmon_battery_current", "legendFormat": "Battery Volts" }
   ]
  },
  {
   "title": "Battery Temperature (F)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "expr": "solarmon_battery_temperature_celsius * 1.8 + 32",
     "legendFormat": "Battery Temp"
    }
   ]
  },
  {
   "title": "Controller Temperature (F)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "expr": "solarmon_controller_temperature_celsius * 1.8 + 32",
     "legendFormat": "Controller Temp"
    }
   ]
  },
  {
   "title": "Raspberry Pi Temp (F)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "expr": "pi_temperature_celcius * 1.8 + 32",
     "legendFormat": "Raspberry Pi Temp"
    }
   ]
  }
 ]
}