{
 "title": "Solar Bluetooth Monitor - History",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Solar Charge (W)",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "targets": [
    { "expr": "solarmon_solar_watts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Power Generation (Total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarmon_power_generation_total",
     "legendFormat": "Solar Amps"
    }
   ]
  },
  {
   "title": "View Options",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "options": {
    "content": "<div class=\"gf-form\">\r\n  <a class=\"gf-form-label gf-form-label\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-03/solar-bluetooth-monitor-history?orgId=1&refresh=30s&from=now-7d&to=now&kiosk\">1w</a>\r\n  <a class=\"gf-form-label gf-form-label\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-03/solar-bluetooth-monitor-history?orgId=1&refresh=30s&from=now-28d&to=now&kiosk\">4w</a>\r\n  <a class=\"gf-form-label gf-form-label\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-03/solar-bluetooth-monitor-history?orgId=1&refresh=30s&from=now-3M&to=now&kiosk\">3m</a>\r\n  <a class=\"gf-form-label gf-form-label\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-03/solar-bluetooth-monitor-history?orgId=1&refresh=30s&from=now-6M&to=now&kiosk\">6m</a>\r\n</div>\r\n<div class=\"gf-form\">\r\n  <a class=\"gf-form-label gf-form-label--dashlink\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-01/solar-bluetooth-monitor?orgId=1&refresh=30s&from=now-7d&to=now&kiosk\">MAIN</a>\r\n  <a class=\"gf-form-label gf-form-label--dashlink\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-04/solar-bluetooth-monitor-more?orgId=1&refresh=30s&from=now-7d&to=now&kiosk\">CHARTS</a>\r\n</div>\r\n<div class=\"gf-form\">\r\n  <a class=\"gf-form-label gf-form-label--dashlink\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:3000/d/solarmon-03/solar-bluetooth-monitor-history?orgId=1&refresh=30s&kiosk=tv\">SHOW DASH</a>\r\n  <a class=\"gf-form-label gf-form-label--dashlink\" style=\"font-size: 1.5em;\" href=\"http://solar-monitor.local:7800/\">EXIT</a>\r\n</div>\r\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Battery Charge (%)",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 7 },
   "targets": [
    { "expr": "solarmon_battery_percentage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Controller Temp (C)",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "solarmon_controller_temperature_celsius",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raspberry Pi Temp (C)",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "pi_temperature_celcius", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Volts (V)",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    { "expr": "solarmon_battery_volts", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Raspberry Pi RAM Usage (%)",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    { "expr": "pi_ram_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Raspberry Pi CPU Usage (%)",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    { "expr": "pi_cpu_usage", "legendFormat": "__auto" }
   ]
  }
 ]
}